name: Validate RR

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  compile:
    environment: staging
    name: Compile TS (tsc)
    runs-on: ubuntu-latest
    steps:
      - name : ğŸ“¦ Checkout project repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      
      - name: Generate and load .env file
        run: |
          printenv | grep "RN" >> .env.${{ secrets.ENVIRONMENT }}
          export $(cat .env.${{ secrets.ENVIRONMENT }} | xargs)
          echo $(cat .env.${{ secrets.ENVIRONMENT }})
        env:
          RN_API_URL: ${{ secrets.RN_API_URL }}
          RN_EAS_PROJECT_ID: ${{ secrets.RN_EAS_PROJECT_ID }}

      - name: ğŸ“¦ Install Reviewdog
        uses: reviewdog/action-setup@v1

      - name: ğŸ“¦ Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: ğŸ“¦ Restore Project Dependencies (node_modules)
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: ğŸ“¦ Install Project Dependencies
        env:
          APP_ENV: ${{ secrets.ENVIRONMENT }}
        run: yarn install --immutable

      - name: ğŸƒâ€â™‚ï¸ Run TypeScript # Reviewdog tsc errorformat: %f:%l:%c - error TS%n: %m
        run: |
          yarn type-check | reviewdog -name="tsc" -efm="%f(%l,%c): error TS%n: %m" -reporter="github-pr-review" -filter-mode="nofilter" -fail-on-error -tee
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  lint:
    environment: staging
    name: Lint TS (eslint, prettier)
    runs-on: ubuntu-latest

    steps:
      - name : ğŸ“¦ Checkout project repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      
      - name: Generate and load .env file
        run: |
          printenv | grep "RN" >> .env.${{ secrets.ENVIRONMENT }}
          export $(cat .env.${{ secrets.ENVIRONMENT }} | xargs)
          echo $(cat .env.${{ secrets.ENVIRONMENT }})
        env:
          RN_API_URL: ${{ secrets.RN_API_URL }}
          RN_EAS_PROJECT_ID: ${{ secrets.RN_EAS_PROJECT_ID }}
  
      - name: ğŸ“¦ Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: ğŸ“¦ Restore Project Dependencies (node_modules)
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: ğŸ“¦ Install Project Dependencies
        env:
          APP_ENV: ${{ secrets.ENVIRONMENT }}
        run: yarn install --immutable

      - name: ğŸƒâ€â™‚ï¸ Run ESLint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: '. --ext .js,.jsx,.ts,.tsx'

  test:
    environment: staging
    name: Tests (jest)
    runs-on: ubuntu-latest

    steps:
      - name : ğŸ“¦ Checkout project repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      
      - name: Generate and load .env file
        run: |
          printenv | grep "RN" >> .env.${{ secrets.ENVIRONMENT }}
          export $(cat .env.${{ secrets.ENVIRONMENT }} | xargs)
          echo $(cat .env.${{ secrets.ENVIRONMENT }})
        env:
          RN_API_URL: ${{ secrets.RN_API_URL }}
          RN_EAS_PROJECT_ID: ${{ secrets.RN_EAS_PROJECT_ID }}  

      - name: ğŸ“¦ Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: ğŸ“¦ Restore Project Dependencies (node_modules)
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: ğŸ“¦ Install Project Dependencies
        env:
          APP_ENV: ${{ secrets.ENVIRONMENT }}
        run: yarn install --immutable

      - name: ğŸƒâ€â™‚ï¸ Run Tests
        run: yarn test:ci